# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: agent_pool_hdo4 # or the name of your self-hosted agent pool
  demands: agent.name -equals hdo4

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.105'
    
- script: dotnet build
  displayName: 'Build the projects'

- script: dotnet pack
  displayName: 'Package the project'

- script: dotnet nuget push bin/*.nupkg --source https://pkgs.dev.azure.com/theamirocohen/_packaging/hdo4_feed_temp/nuget/v3/index.json --api-key $(System.AccessToken)
  displayName: 'Push to Azure Artifacts'
